version: '3.4'

services:
  telegrambot-to-wordpress:
    image: ${DOCKER_REGISTRY-}telegrambot-to-wordpress
    build:
      context: .
      dockerfile: src/TelegramBotToWordPress/Dockerfile
    environment:
      wp-baseurl: 123
      wp-blogid: 1
      wp-username: 123
      wp-password: 123
      wp-parentid: 37292
      wp-author: 1
      bot-apikey: 123

